#config.yaml
controlador:
  id: 1
  ip: "192.168.0.1"
  sensores:
    - id: 1
      nombre: "mod 1"
      vm: 0
      parametro_minimo: 400
      parametro_maximo: 800
      actuadores_asociados: [1]
    - id: 2
      nombre: "mod 2"
      vm: 2
      parametro_minimo: 500
      parametro_maximo: 650
      actuadores_asociados: []
  actuadores:
    - id: 1
      nombre: "LUZ VERDE"
      marca_arranque: "M1"
      estado: "M3"
      estado_plc: "M2"
    - id: 2
      nombre: "vacio"
      marca_arranque: ""
      estado: "M10"
      estado_plc: "M11"

raspberry:
  ip_eth: "192.168.0.31"
  ip_wlan: "192.168.1.31"
  ip_wireguard: "10.0.0.1"
  ip_router: "192.168.1.1"


intervalos:
  intervalo_collectorA: 60       # en segundos (actuadores)
  intervalo_collectorS: 31      # en segundos (sensores)
  intervalo_schedulerA: 1100      # en segundos (actuadores)
  intervalo_schedulerS: 600      # en segundos (sensores)